language: python
python:
  - '3.6'
  - '3.7'
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
install:
  - pip install pipenv
  - pipenv install
script:
  - python tests.py